package pl.rstepniewski.sockets.server;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import pl.rstepniewski.sockets.dto.ShotDto;
import pl.rstepniewski.sockets.game.*;
import pl.rstepniewski.sockets.game.board.BoardCellStatus;
import pl.rstepniewski.sockets.game.board.GameBoard;
import pl.rstepniewski.sockets.game.board.GameBoardAIController;
import pl.rstepniewski.sockets.game.fleet.FleetLoader;
import pl.rstepniewski.sockets.jsonCommunication.Request;
import pl.rstepniewski.sockets.jsonCommunication.RequestType;
import pl.rstepniewski.sockets.jsonCommunication.Response;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;

import static pl.rstepniewski.sockets.jsonCommunication.ResponseType.GAME_INVITATION;

/**
 * Created by rafal on 09.06.2023
 *
 * @author : rafal
 * @date : 09.06.2023
 * @project : Battleship
 */
public class ServerCommunicator {
    private static final Logger logger = LogManager.getLogger(ServerCommunicator.class);
    private final GameBoardAIController gameBoardAIController;
    private final ObjectMapper objectMapper = new ObjectMapper();

    private final BufferedReader bufferedReader;
    private final PrintWriter printWriter;
    private final ServerService serverService;
    private String jsonString;
    private Request request;
    private Response response;

    public ServerCommunicator(ServerService serverService) {
        this.bufferedReader         = serverService.getBufferedReader();
        this.gameBoardAIController  = new GameBoardAIController(new GameBoard(), new FleetLoader());
        this.printWriter            = serverService.getPrintWriter();
        this.serverService          = serverService;
    }

    public void handleGame() throws IOException {
        handleGameInvitation();
        gameBoardAIController.initialiseBord();

        while (gameBoardAIController.isFleetAlive()) {
            Request shotRequest = getShotRequest();
            handleShotRequest(shotRequest);

            Point shot = shoot();
            response = getShotResut();
            markShootResut(shot, response);
        }
    }

    private void handleGameInvitation() throws IOException {
        jsonString = bufferedReader.readLine();
        request = objectMapper.readValue(jsonString, Request.class);
        logger.info("Request received from client. Request type: " + request.type());

        if(!request.type().equals(GAME_INVITATION.name())) {
            response = Response.gameInvitationNegative();
            String gameInvitationNegativeResponse = objectMapper.writeValueAsString(response);
            printWriter.println(gameInvitationNegativeResponse);
            logger.info("Server decline game invitation");
        }
        response = Response.gameInvitationNegative();
        String gameInvitationPositiveResponse = objectMapper.writeValueAsString(response);
        printWriter.println(gameInvitationPositiveResponse);
        logger.info("Server accepted game invitation");
    }

    private void markShootResut(Point shot, Response response) {
        if (response.status() == 2) {
            UserInterface.printText(response.message().toString());
        }
        switch (response.body().toString()) {
            case "HIT":
                gameBoardAIController.markHitOnShotBoard(shot);
                break;
            case "MISS":
                gameBoardAIController.markMissOnShotBoard(shot);
                break;
            case "SINKING":
                gameBoardAIController.markSinkingOnShotBoard(shot);
        }
    }

    private Response getShotResut() throws IOException {
        String responseJson = bufferedReader.readLine();
        return objectMapper.readValue(responseJson, Response.class);
    }

    private Point shoot() throws JsonProcessingException {
        Point shot = gameBoardAIController.getNewRandomShot();

        logger.info("The coordinates of the shot generated by server are x:" + shot.getX() + " y:" + shot.getY());
        Request request = Request.shot( new ShotDto(shot.getX(), shot.getY()) );
        String json = objectMapper.writeValueAsString(request);
        printWriter.println(json);
        return shot;
    }

    private Request getShotRequest() throws IOException {
        jsonString = bufferedReader.readLine();
        request = objectMapper.readValue(jsonString, Request.class);
        logger.info("The coordinates of the shot sent by user: "+ request.body().toString());
        return request;
    }

    private void handleShotRequest(Request request) throws IOException {
        if (request.type().equals(RequestType.SHOT.name())) {
            ShotDto point = objectMapper.readValue(objectMapper.writeValueAsString(request.body()), ShotDto.class);
            Point receivedShot = new Point(point.getX(), point.getY());
            boolean isShotAccurate = gameBoardAIController.isShotHit(receivedShot);
            gameBoardAIController.reportReceivedShot(receivedShot);
            String gameShotStatusResponse;
            if (isShotAccurate) {
                boolean isShipSinking = gameBoardAIController.markHitOnShipBoard(receivedShot);
                gameBoardAIController.markHitOnFleetBoard(receivedShot, BoardCellStatus.HIT);
                if (isShipSinking) {
                    gameShotStatusResponse = objectMapper.writeValueAsString(Response.shotResultSinking());
                    printWriter.println(gameShotStatusResponse);
                } else {
                    gameShotStatusResponse = objectMapper.writeValueAsString(Response.shotResultHit());
                    printWriter.println(gameShotStatusResponse);
                }
            } else {
                gameBoardAIController.markHitOnFleetBoard(receivedShot, BoardCellStatus.MISS);
                gameShotStatusResponse = objectMapper.writeValueAsString(Response.shotResultMiss());
                printWriter.println(gameShotStatusResponse);
            }
            System.out.println(gameShotStatusResponse);
        }
    }
}
